---
title: "covid_generalized_linear_model"
author: "Claudia Quintana Wong"
date: "26/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
```


## Introducción


## Desarrollo

En esta sección ...

### Descripción del *dataset*


### Carga y transformación

```{r}
original.data <- read.csv(file = 'data/owid-covid-data.csv')
summary(original.data)
```

### Análisis descriptivo

```{r}
europe.data <- original.data %>% 
  select(continent, location, date, new_cases, new_deaths, reproduction_rate,
         hosp_patients, icu_patients, hospital_beds_per_thousand, new_tests, positive_rate, population) %>% 
  filter(continent == 'Europe', date >= '2020-07-01', location == 'Spain')

```


```{r}
summary(europe.data)
```

```{r}
data.path = "data/csse_covid_19_daily_reports_us"

data.df <- read.csv(file = "data/csse_covid_19_daily_reports_us/07-01-2020.csv")
data.df$Date <- "2020-07-1"

file_list <- list.files(path=data.path)

for (f in file_list){
  str.date = substring(f, 1, 10)
  date <- as.Date(str.date, format="%d-%m-%Y")
  print(f)
  if (!is.na(date) & date > "2020-07-01"){
    filepath = paste(data.path, "/", f, sep="")
    data <- read.csv(file = filepath, header=F)
    data$Date <- str.date
    names(data) <- names(data.df) 
    data.df <- rbind(data.df, data)
  }
  
}
```




### Modelo de regresión



## Including Plots




## Conclusiones